#!/bin/bash

cd /usr/share/lubuntu/wallpapers/
if [ -f 1804-lubuntu-default-wallpaper.png ]; then
	mv 1804-lubuntu-default-wallpaper.png lubuntu-original-wallpaper.png
	mv wx_wallpaper.png 1804-lubuntu-default-wallpaper.png
fi

if [ -f 2004-lubuntu-wire-humming.png ]; then
	mv 2004-lubuntu-wire-humming.png lubuntu-original-wallpaper.png
	mv wx_wallpaper.png 2004-lubuntu-wire-humming.png
	rm -rf /home/*/.cache
fi
